project:
  type: website
  output-dir: docs

website:
  title: "yschin03.github.io"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: about.qmd
        text: My Project

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

